INSERT INTO Stations (code, name, city, state) VALUES
('SBC', 'KSR Bengaluru', 'Bengaluru', 'Karnataka'),
('MYS', 'Mysuru Junction', 'Mysuru', 'Karnataka'),
('MAS', 'Chennai Central', 'Chennai', 'Tamil Nadu'),
('HYB', 'Hyderabad Deccan', 'Hyderabad', 'Telangana'),
('NDLS', 'New Delhi', 'New Delhi', 'Delhi'),
('CSMT', 'Chhatrapati Shivaji Maharaj Terminus', 'Mumbai', 'Maharashtra');

INSERT INTO Trains (train_number, train_name, train_type, total_seats, available_classes) VALUES
('12007', 'Shatabdi Express', 'Superfast', 500, 'Chair Car,Executive Class'),
('12627', 'Karnataka Express', 'Express', 800, 'Sleeper,AC 3 Tier,AC 2 Tier,AC First Class'),
('22691', 'Rajdhani Express', 'Premium', 600, 'AC 3 Tier,AC 2 Tier,AC First Class'),
('20607', 'Vande Bharat Express', 'Premium', 400, 'Chair Car,Executive Class');

INSERT INTO Buses (bus_number, operator_name, bus_type, total_seats) VALUES
('KA-01-F-1234', 'KSRTC Airavat', 'AC Sleeper', 40),
('TN-02-B-5678', 'SRS Travels', 'AC Seater', 50),
('MH-03-C-9012', 'VRL Travels', 'Non-AC Sleeper', 35);

INSERT INTO Users (name, email, password_hash, mobile_number, role) VALUES
('Admin User', 'admin@sbrb.com', '$2a$10$xyz', '9999999999', 'Admin'),
('Employee User', 'employee@sbrb.com', '$2a$10$xyz', '8888888888', 'Employee'),
('John Doe', 'john@example.com', '$2a$10$xyz', '7777777777', 'Customer');

-- Password hash needs to be generated by bcrypt in actual application. We just mock it here.
